name: validicitylib
description: A shared library for the Validicity system
version: 0.1.0
homepage: https://www.validicity.com
author: Göran Krampe <goran.krampe@gmail.com>
publish_to: none

environment:
  sdk: '>=2.7.0'

dependencies:
  ed25519_dart:
    git:
      url: https://github.com/getcanoe/ed25519_dart
      ref: master
  args: ^1.6.0
  checked_yaml: ^1.0.2
  http: ^0.12.0+4
  json_annotation: ^3.0.0
  logging: ^0.11.4
  mqtt_client: ^7.2.1
  nanodart: ^1.0.0
  oauth2: ^1.6.1

dev_dependencies:
  aqueduct_test:
    git:
      url: git://github.com/gokr/aqueduct.git
      path: aqueduct_test
  build_runner: ^1.10.0
  json_serializable: ^3.0.0
  test: ^1.15.1
