name: validicitylib
description: A shared library for the Validicity system
version: 0.1.0
homepage: https://www.validicity.com
author: Göran Krampe <goran.krampe@gmail.com>

environment:
  sdk: '>=2.7.0'

dependencies:
  args: ^1.6.0
  http: ^0.12.0+4
  logging: ^0.11.4
  checked_yaml: ^1.0.2
  mqtt_client: ^6.2.1
  oauth2: ^1.5.0
  json_annotation: ^3.0.0
  hive: ^1.4.1
  nanodart: ^1.0.0

dev_dependencies:
  build_runner: ^1.8.1
  hive_generator: ^0.7.0
  test: ^1.12.0
  # aqueduct_test is nice for doing http test code
  aqueduct_test:
    git:
      url: git://github.com/gokr/aqueduct.git
      path: aqueduct_test
  json_serializable: ^3.3.0
